Bus:
  _xpath: ".//CAN-CLUSTER"
  BusName: "SHORT-NAME"
  BusBaudRate: "CAN-CLUSTER-VARIANTS/CAN-CLUSTER-CONDITIONAL/BAUDRATE"
  BusPhyName: "CAN-CLUSTER-VARIANTS/CAN-CLUSTER-CONDITIONAL/PHYSICAL-CHANNELS/CAN-PHYSICAL-CHANNEL/SHORT-NAME"
  CanFDBaudrate: "CAN-CLUSTER-VARIANTS/CAN-CLUSTER-CONDITIONAL/CAN-FD-BAUDRATE"
  CanMsgList:
    _xpath: "CAN-CLUSTER-VARIANTS/CAN-CLUSTER-CONDITIONAL/PHYSICAL-CHANNELS/CAN-PHYSICAL-CHANNEL/FRAME-TRIGGERINGS/CAN-FRAME-TRIGGERING"
    FrameId: "IDENTIFIER"
    FrameLen: "&(FRAME-REF)FRAME-LENGTH"
    FrameName: "&(FRAME-REF)SHORT-NAME"
    FrameDirection: "&(FRAME-PORT-REFS/FRAME-PORT-REF)COMMUNICATION-DIRECTION"
    FramePacking: "&(FRAME-REF)PDU-TO-FRAME-MAPPINGS/PDU-TO-FRAME-MAPPING/PACKING-BYTE-ORDER"
    FrameStartPos: "&(FRAME-REF)PDU-TO-FRAME-MAPPINGS/PDU-TO-FRAME-MAPPING/START-POSITION"
    CanAddrMode: "CAN-ADDRESSING-MODE"
    CanFrameRxBehv: "CAN-FRAME-RX-BEHAVIOR"
    CanFrameTxBehv: "CAN-FRAME-TX-BEHAVIOR"
    PduList:
      _xref: "PDU-TRIGGERINGS/PDU-TRIGGERING-REF-CONDITIONAL/PDU-TRIGGERING-REF"
      PduTrigName: "SHORT-NAME"
      PduName: "&(I-PDU-REF)SHORT-NAME"
      Pdulen: "&(I-PDU-REF)LENGTH"
      PduTxModeTimeperiod: "&(I-PDU-REF)I-PDU-TIMING-SPECIFICATIONS/I-PDU-TIMING/TRANSMISSION-MODE-DECLARATION/TRANSMISSION-MODE-TRUE-TIMING/CYCLIC-TIMING/TIME-PERIOD/VALUE"
      
      SigReflist:
        _xref: "I-PDU-REF"
        Siglist:
          _xpath: "./I-SIGNAL-TO-PDU-MAPPINGS/I-SIGNAL-TO-I-PDU-MAPPING" 
          Signame: "SHORT-NAME"
          SigInitValue: "&(I-SIGNAL-REF)INIT-VALUE/*/VALUE"
          SigBitLen: "&(I-SIGNAL-REF)LENGTH"
          SigStartPos: "START-POSITION"
          SigPackByteOrder: "PACKING-BYTE-ORDER"
      
      # SigList:
        # _xref: "I-PDU-REF"
        # Signame: "&(I-PDU-REF)I-SIGNAL-TO-PDU-MAPPINGS/I-SIGNAL-TO-I-PDU-MAPPING/SHORT-NAME"
        # SigStartPos: "&(I-PDU-REF)I-SIGNAL-TO-PDU-MAPPINGS/I-SIGNAL-TO-I-PDU-MAPPING/START-POSITION"
        # SigPackByteOrder: "&(I-PDU-REF)I-SIGNAL-TO-PDU-MAPPINGS/I-SIGNAL-TO-I-PDU-MAPPING/PACKING-BYTE-ORDER"
        
        
    # FrameInfo: 
      # _xref: "FRAME-REF"
      # FrameName: "SHORT-NAME"
      # FramePacking: "PDU-TO-FRAME-MAPPINGS/PDU-TO-FRAME-MAPPING/PACKING-BYTE-ORDER"
      # FrameStartPos: "PDU-TO-FRAME-MAPPINGS/PDU-TO-FRAME-MAPPING/START-POSITION"
      # PduTrigname : "&(./PDU-TRIGGERINGS/PDU-TRIGGERING-REF-CONDITIONAL/PDU-TRIGGERING-REF)SHORT-NAME"
    # PduInfo:
      # _xref: "&(PDU-TRIGGERINGS/PDU-TRIGGERING-REF-CONDITIONAL/PDU-TRIGGERING-REF)SHORT-NAME"
      # PduTrigname: "SHORT-NAME"
    # Siginfo:
      # _xref: "PDU-TRIGGERINGS/PDU-TRIGGERING-REF-CONDITIONAL/PDU-TRIGGERING-REF/I-SIGNAL-TRIGGERINGS/I-SIGNAL-TRIGGERING-REF-CONDITIONAL/I-SIGNAL-TRIGGERING-REF"
      # SigTrigName: "SHORT-NAME"

# PDU:
  # _xpath: ".//I-SIGNAL-I-PDU"
  # Name: "SHORT-NAME"
  # Length: "text>int:LENGTH"
  # CyclicTiming: "text>float:.//TRANSMISSION-MODE-TRUE-TIMING/CYCLIC-TIMING/TIME-PERIOD/VALUE"
  # SignalMappings:
    # _xpath: ".//I-SIGNAL-TO-I-PDU-MAPPING"
    # Signal: "SHORT-NAME"
    # StartPosition: "text>int:START-POSITION"
    # ISignal:
      # _xref: "I-SIGNAL-REF"
      # InitValue: "text>int:.//VALUE"
      # Length: "text>int:LENGTH"